activity/urls.py
from django.conf.urls import url

from activity.views.training import *

urlpatterns = [
    url(r'thamatic/list/$', ThematicAreaListView.as_view(), name='thematic_list'),
    url(r'thamatic/create/$',  ThematicAreaCreateView.as_view(), name='thamatic_create'),
    url(r'thamatic/(?P<pk>[\w]+)/$', ThematicAreaUpdateView.as_view(), name='thamatic_edit'),
    url(r'training/session/(?P<pk>[\w]+)/$', TrainingSessionDetailView.as_view(), name='detail_list'),
    url(r'training/session/$', TrainingSessionListView.as_view(), name='training_list'),
    url(r'training/create/$', TrainingCreateView.as_view(), name='training_create'),
    url(r'external/create/$', ExternalTrainerCreateView.as_view(), name='external_create'),

    url(r'training/topic/list/(?P<thematic>[\w]+)/$', TrainingContentListView.as_view(), name='training_content_list'),
    url(r'training/topic/create/(?P<thematic>[\w]+)/$', TrainingContentCreateView.as_view(), name='training_coontent_create'),
    url(r'training/topic/create/(?P<thematic>[\w]+)/update/(?P<pk>[\w]+)/$', TrainingContentUpdateView.as_view(), name='training_coontent_update'),
]

conf/urls.py
from django.conf.urls import url

from conf.views import *

urlpatterns = [
     url(r'sms/template/$', MessageTemplatesView.as_view(), name='sms_template'),
     url(r'district/list/$', DistrictListView.as_view(), name='district_list'),
     url(r'district/create/$', DistrictCreateView.as_view(), name='district_create'),
     url(r'district/(?P<pk>[\w]+)/$', DistrictUpdateView.as_view(), name='district_edit'),
     url(r'district/delete/(?P<pk>[\w]+)/$', DistrictDeleteView.as_view(), name='district_delete'),
     url(r'county/create/$', CountyCreateView.as_view(), name='county_create'),
     url(r'county/list/$', CountyListView.as_view(), name='county_list'),
     url(r'county/(?P<pk>[\w]+)/$', CountyUpdateView.as_view(), name='county_edit'),

     url(r'sc/create/$', SubCountyCreateView.as_view(), name='subcounty_create'),
     url(r'sc/list/$', SubCountyListView.as_view(), name='subcounty_list'),
     url(r'sc/(?P<pk>[\w]+)/$', SubCountyUpdateView.as_view(), name='subcounty_edit'),
     url(r'village/create/$', VillageCreateView.as_view(), name='village_create'),
     url(r'village/list/$', VillageListView.as_view(), name='village_list'),
     url(r'village/(?P<pk>[\w]+)/$', VillageUpdateView.as_view(), name='village_edit'),
     url(r'payment/create/$', PaymentModeCreateView.as_view(), name='payment_create'),
     url(r'payment/list/$', PaymentModeListView.as_view(), name='payment_list'),
     url(r'payment/(?P<pk>[\w]+)/$', PaymentModeUpdateView.as_view(), name='payment_edit'),
     
     url(r'upload/location/$', LocationUploadView.as_view(), name='location_upload'),
    ]

coop/urls.py
from django.conf.urls import url

from coop.views.cooperative import *
from coop.views.member import *
from coop.views.collection import *
from coop.views.order import *
from coop.views.agent import *
from coop.views.farmer_group import *

urlpatterns = [

     url(r'agent/list/$', AgentListView.as_view(), name='agent_list'),
     url(r'agent/create/$', AgentCreateFormView.as_view(), name='agent_create'),
    
     url(r'order/status/(?P<pk>[\w]+)/(?P<status>[\w]+)$', MemberOrderStatusView.as_view(), name='order_status'),
     url(r'order/item/list/$', MemberOrderItemListView.as_view(), name='order_item_list'),
     url(r'order/item/status/(?P<pk>[\w]+)/(?P<status>[\w]+)$', OrderItemStatusView.as_view(), name='item_status'),

     url(r'order/delete/(?P<pk>[\w]+)/$', MemberOrderDeleteView.as_view(), name='order_delete'),
     url(r'order/detail/(?P<pk>[\w]+)/$', MemberOrderDetailView.as_view(), name='order_detail'),
     url(r'order/payment/(?P<pk>[\w]+)/$', OrderPaymentView.as_view(), name='order_payment'),
     url(r'order/create/(?P<pk>[\w]+)/$', MemberOrderCreateView.as_view(), name='order_update'),
     url(r'order/create/$', MemberOrderCreateView.as_view(), name='order_create'),
     url(r'order/list/$', MemberOrderListView.as_view(), name='order_list'),
    
     url(r'collection/download/$', CollectionDownload.as_view(), name='collection_download'),
     url(r'collection/create/$', CollectionCreateView.as_view(), name='collection_update'),
     url(r'collection/create/$', CollectionCreateView.as_view(), name='collection_create'),
     url(r'collection/list/$', CollectionListView.as_view(), name='collection_list'),
     url(r'collection/upload/$', CollectionUploadView.as_view(), name='collection_upload'),

     url(r'member/shares/$', MemberSharesView.as_view(), name='member_shares'),
     
     url(r'member/shares/list/(?P<member>[\w]+)/$', MemberSharesListView.as_view(), name='member_shares_list'),
     url(r'member/shares/list/$', MemberSharesListView.as_view(), name='member_shares_list'),
     url(r'member/shares/create/$', MemberSharesCreateView.as_view(), name='member_shares_create'),
     url(r'member/shares/(?P<pk>[\w]+)/$', MemberSharesUpdateView.as_view(), name='member_shares_update'),
     
     url(r'member/subscription/list/$', MemberSubscriptionListView.as_view(), name='member_subscription_list'),
     url(r'member/subscription/create/$', MemberSubscriptionCreateView.as_view(), name='member_subscription_create'),
     url(r'member/subscription/(?P<pk>[\w]+)/$', MemberSubscriptionUpdateView.as_view(), name='member_subscription_update'),
     
     url(r'share/price/list/$', CooperativeSharePriceListView.as_view(), name='share_price_list'),
     url(r'share/price/create/$', CooperativeSharePriceCreateView.as_view(), name='share_price_create'),
     url(r'share/price/(?P<pk>[\w]+)/$', CooperativeSharePriceUpdateView.as_view(), name='share_price_update'),

     url(r'member/insurance/create/(?P<pk>[\w]+)/$', OKOCreatePolicyView.as_view(), name='member_insurance_create'),
     url(r'member/insurance/check/(?P<pk>[\w]+)/$', OKOCheckPolicyView.as_view(), name='member_insurance_check'),

     url(r'supply/request/list/$', MemberSupplyRequestListView.as_view(), name='request_list'),
     url(r'supply/request/create/$', MemberSupplyRequestCreateView.as_view(), name='request_create'),
     url(r'supply/request/create/(?P<pk>[\w]+)/$', MemberSupplyRequestCreateView.as_view(), name='request_create'),
     url(r'supply/request/detail/(?P<pk>[\w]+)/$', MemberSupplyRequestDetailView.as_view(), name='request_detail'),

     url(r'fg/delete/(?P<pk>[\w]+)/$', FarmerGroupDeleteView.as_view(), name='fg_delete'),
     url(r'fg/update/(?P<pk>[\w]+)/$', FarmerGroupUpdateView.as_view(), name='fg_update'),
     url(r'fg/upload/$', FarmerGroupUploadView.as_view(), name='fg_upload'),
     url(r'fg/create/$', FarmerGroupCreateView.as_view(), name='fg_create'),
     url(r'fg/list/$', FarmerGroupListView.as_view(), name='fg_list'),
     
     
     url(r'ajax/village/$', load_villages, name='ajax_load_village'),
     url(r'ajax/member/$', load_coop_members, name='ajax_load_members'),
     
     url(r'communication/send/$', SendCommunicationView.as_view(), name='communication_send'),
     
     url(r'desease/list/$', CooperateCommonDiseaseListView.as_view(), name='disease_list'),
     url(r'desease/create/$', CooperateCommonDiseaseCreateView.as_view(), name='disease_create'),
     url(r'desease/(?P<pk>[\w]+)/$', CooperateCommonDiseaseUpdateView.as_view(), name='disease_update'),
     
     url(r'contribution/list/$', CooperativeContributionListView.as_view(), name='contribution_list'),
     url(r'contribution/create/$', CooperativeContributionCreateView.as_view(), name='contribution_create'),
     url(r'contribution/(?P<pk>[\w]+)/$', CooperativeContributionUpdateView.as_view(), name='contribution_update'),
     url(r'share/list/$', CooperativeShareTransactionListView.as_view(), name='share_list'),
     url(r'share/create/$', CooperativeShareTransactionCreateView.as_view(), name='share_create'),
     url(r'share/(?P<pk>[\w]+)/$', CooperativeShareTransactionUpdateView.as_view(), name='share_update'),
     url(r'member/delete/(?P<pk>[\w]+)/$', MemberDeleteView.as_view(), name='member_delete'),
     url(r'member/detail/(?P<pk>[\w]+)/$', CooperativeMemberDetailView.as_view(), name='member_detail'),
     url(r'member/qrcode/(?P<pk>[\w]+)/$', ImageQRCodeDownloadView.as_view(), name='member_qrcode'),
     url(r'member/download/$', DownloadExcelMemberView.as_view(), name='member_download'),
     url(r'member/upload/$', MemberUploadExcel.as_view(), name='member_upload'),
     url(r'member/list/$', CooperativeMemberListView.as_view(), name='member_list'),
     url(r'member/create/$', MemberCreateView.as_view(), name='member_create'),
     url(r'member/map/$', MembersMapView.as_view(), name='member_map'),
     url(r'member/(?P<pk>[\w]+)/$', MemberUpdateView.as_view(), name='member_update'),
     url(r'delete/(?P<pk>[\w]+)/$', CooperativeDeleteView.as_view(), name='delete'),
     url(r'upload/$', CooperativeUploadView.as_view(), name='upload'),
     url(r'create/$', CooperativeCreateView.as_view(), name='create'),
     url(r'list/$', CooperativeListView.as_view(), name='list'),
     url(r'ajax/load-farmer/', get_farmer_map, name='ajax_load_farmer_map'),
     url(r'(?P<pk>[\w]+)/$', CooperativeUpdateView.as_view(), name='edit'),
     
    ]

umis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from conf import urls as conf_urls
from userprofile import urls as profile_urls
from product import urls as product_urls
from coop import urls as coop_urls 
from partner import urls as partner_urls
from operations import urls as op_urls
from endpoint import urls as ep_urls
from messaging import urls as msg_urls
from activity import urls as act_urls
from payment import urls as pay_urls
from credit import urls as credit_urls
from account import urls as account_urls

from dashboard.views import DashboardView
from userprofile.views.authentication import LoginView, LogoutView
from conf.views import Handle404, Handle403

handler404 = Handle404.as_view()
handler403 = Handle403.as_view()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^conf/', include(conf_urls, namespace='conf')),
    url(r'^profile/', include(profile_urls, namespace='profile')),
    url(r'^product/', include(product_urls, namespace='product')),
    url(r'^payment/', include(pay_urls, namespace='payment')),
    url(r'^coop/', include(coop_urls, namespace='coop')),
    url(r'^op/', include(op_urls, namespace='op')),
    url(r'^partner/', include(partner_urls, namespace='partner')),
    url(r'^endpoint/', include(ep_urls, namespace='endpoint')),
    url(r'^messaging/', include(msg_urls, namespace='messaging')),
    url(r'^activity/', include(act_urls, namespace='activity')),
    url(r'^credit/', include(credit_urls, namespace='credit')),
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

activity/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from django.db import models
from django.contrib.auth.models import User
from coop.models import CooperativeMember, Cooperative
from product.models import ProductVariation

class ThematicArea(models.Model):
    thematic_area = models.CharField(max_length=150)
    description = models.TextField(null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'thematic_area'
        
    def __unicode__(self):
        return self.thematic_area


class TrainingModule(models.Model):
    thematic_area = models.ForeignKey(ThematicArea, on_delete=models.CASCADE)
    topic = models.CharField(max_length=250)
    descriprion = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(User, null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'training_module'
        
    def __unicode__(self):
        return "%s" % self.module


class TrainingAttendance(models.Model):
    training_module = models.ForeignKey(TrainingModule, null=True, blank=True, on_delete=models.CASCADE)
    training_reference = models.CharField(max_length=256, null=True, blank=True)
    trainer = models.ForeignKey(User, related_name='trainer', on_delete=models.CASCADE)
    coop_member = models.ManyToManyField(CooperativeMember, blank=True)
    gps_location = models.CharField(max_length=256, null=True, blank=True)
    training_start = models.DateTimeField()
    training_end = models.DateTimeField()
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'training_attendance'
        
    def __unicode__(self):
        return "%s" % self.coop_member
    
    def trainer_is_cooperative(self):
        if self.trainer.cooperative_admin:
            return True
        return False
    
class ExternalTrainer(models.Model):
    name = models.CharField(max_length=255)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "external_trainer"
        
    def __unicode__(self):
        return self.name


class TrainingTopic(models.Model):
    thematic_area = models.ForeignKey(ThematicArea, on_delete=models.CASCADE)
    topic = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "training_topic"


class TrainingContent(models.Model):
    thematic_area = models.ForeignKey(ThematicArea, null=True, blank=True, on_delete=models.CASCADE)
    sequence = models.IntegerField(null=True)
    topic = models.CharField(max_length=255)
    content = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)


    class Meta:
        db_table = "training_content"
        unique_together = ['thematic_area', 'sequence']

    
    
class TrainingSession(models.Model):
    thematic_area = models.ForeignKey(ThematicArea, null=True, blank=True, on_delete=models.CASCADE)
    training_reference = models.CharField(max_length=256, null=True, blank=True)
    trainer = models.ForeignKey(User, related_name='training_officer', null=True, blank=True, on_delete=models.CASCADE)
    is_external = models.BooleanField(default=False)
    external_trainer = models.ForeignKey(ExternalTrainer, null=True, blank=True, on_delete=models.CASCADE)
    topic = models.CharField(max_length=256, null=True, blank=True)
    descriprion = models.TextField(null=True, blank=True)
    cooperative = models.ForeignKey(Cooperative, null=True, blank=True, on_delete=models.CASCADE)
    coop_member = models.ManyToManyField(CooperativeMember, blank=True)
    gps_location = models.CharField(max_length=256, null=True, blank=True)
    training_start = models.DateTimeField()
    training_end = models.DateTimeField()
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'training_session'
        
    def __unicode__(self):
        return self.training_reference
    
    def duration(self):
        if self.training_start and self.training_end:
            start = "%s" % (self.training_start)
            end = "%s" % (self.training_end)
            time1 = datetime.datetime.strptime(start[:19],'%Y-%m-%d %H:%M:%S')
            time2 = datetime.datetime.strptime(end[:19],'%Y-%m-%d %H:%M:%S')
            difference = time2-time1
            return difference
    
    
 
class Visit(models.Model):
    coop_member = models.ForeignKey(CooperativeMember, on_delete=models.CASCADE)
    visit_date = models.DateField()
    reason = models.CharField(max_length=160)
    description = models.TextField(null=True, blank=True)
    gps_coodinates = models.CharField(max_length=256, null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'partner_visit'
        
    def __unicode__(self):
        return "%s" % self.coop_member

activity/templates/activity/thematicarea_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">Thematic Areas</h4>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'activity:thamatic_create' %}" class="md-btn md-btn-success uk-float-right">Add Thematic Area</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table id="dt_tableTools" class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Thematice Area</th>
                        <th>Desctiption</th>
                        <th>Update Date</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.thematic_area }}</td>
                                <td>{{ item.description }}</td>
                                <td>{{ item.update_date }}</td>
                                <td class="uk-float-right">
                                    <a href="{% url 'activity:training_content_list' item.id %}" class="md-btn md-btn-default uk-float-right">OPEN</a>
                                    <a href="{% url 'activity:thamatic_edit' item.id %}"><i class="md-icon material-icons">&#xE254;</i></a>
                                </td>
                            </tr>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
           
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <!-- datatables -->
    <script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <!-- datatables colVis-->
    <script src="{% static 'bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
<!-- datatables tableTools-->
    <script src="{% static 'bower_components/datatables-tabletools/js/dataTables.tableTools.js' %}"></script>
    <!-- datatables custom integration -->
    <script src="{% static 'assets/js/custom/datatables_uikit.min.js' %}"></script>

    <!--  datatables functions -->
    <script src="{% static 'assets/js/pages/plugins_datatables.min.js' %}"></script>
{% endblock %}

activity/templates/activity/trainingcontent_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %}

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">Thematic Areas: {{ thematic_area }}</h4>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'activity:training_coontent_create' thematic_area.id %}" class="md-btn md-btn-success uk-float-right">Add Content</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table id="dt_tableTools" class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Thematice Area</th>
                        <th>Topic</th>
                        <th>Update Date</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.thematic_area }}</td>
                                <td>{{ item.topic }}</td>
                                <td>{{ item.update_date }}</td>
                                <td class="uk-float-right">
                                    <a href="{% url 'activity:training_coontent_update' thematic=thematic_area.id pk=item.id %}"><i class="material-icons md-24" title="Edit">border_color</i></a>
                                     {% if request.user.is_superuser %}
                                     {% if item.member_count < 1 %}
                                         <a href="{% url 'coop:delete' item.id %}"><i class="material-icons md-24  uk-text-danger" title="Delete">delete</i></a>
                                     {% endif %}
                                    {% endif %}

                                </td>
                            </tr>

                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <!-- datatables -->
    <script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <!-- datatables colVis-->
    <script src="{% static 'bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
<!-- datatables tableTools-->
    <script src="{% static 'bower_components/datatables-tabletools/js/dataTables.tableTools.js' %}"></script>
    <!-- datatables custom integration -->
    <script src="{% static 'assets/js/custom/datatables_uikit.min.js' %}"></script>

    <!--  datatables functions -->
    <script src="{% static 'assets/js/pages/plugins_datatables.min.js' %}"></script>
{% endblock %}

activity/templates/activity/trainingsession_form.html
{% extends 'base.html' %}
{% load static %}
{% load my_custom_tags %}
{% block style %}
    <!-- additional styles for plugins -->
    <!-- dropify -->
    <link rel="stylesheet" href="{% static 'assets/skins/dropify/css/dropify.css' %}">
    <!-- additional styles for plugins -->
    <!-- kendo UI -->
    <link rel="stylesheet" href="{% static 'bower_components/kendo-ui/styles/kendo.common-material.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'bower_components/kendo-ui/styles/kendo.material.min.css' %}"/>
    <style>
        #id_common_animal_deseases{height: auto !important; min-height: 0px !important;}
    </style>
{% endblock %}
{% block page_content %}
<h3 class="heading_b uk-margin-bottom">Training Session</h3>
   <div class="md-card">
        <div class="md-card-content">
            <form method="POST" class="new-event-form" role="role" enctype="multipart/form-data">
                {% csrf_token %}
                {% include "error_template.html" with form=form %}
                 <div class="uk-grid" data-uk-grid-margin>
                   
                    {% for field in form %}
                    {% if field.name == 'trainer' %}
                    <div class="uk-width-medium-1-1" id="member_wrap">
                        {% elif field.name == 'external_trainer' %}
                        
                    <div class="uk-width-medium-1-1" id="non_member">
                        <a href="{% url 'activity:external_create'%}" style="padding: 50px;"><span class="menu_icon"><i class="fa fa-plus"></i></span> <span class=" class="menu_title">Add External Trainer </span></a>
                    
                    {% else %}
                     <div class="uk-width-medium-1-1">
                    {% endif %}
                    {% include "form/field.html" with field=field input_group_add_on='<i class="uk-input-group-icon uk-icon-map-o"></i>' %}
                    {% if field.name == 'trainer' %}
                        {% endif %}
                    </div>
                     
                     
                    {% endfor %}
                </div>
                
                <div class="uk-grid">
                    <div class="uk-width-1-1">
                        <button type="submit" class="md-btn md-btn-success">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <script src="{% static 'bower_components/parsleyjs/dist/parsley.min.js' %}"></script>
    <!--<!-- jquery steps -->
    <!--<script src="{% static 'assets/js/custom/wizard_steps.min.js' %}"></script>-->
    <!---->
    <!--<!--  forms wizard functions -->
    <!--<script src="{% static 'assets/js/pages/forms_wizard.min.js' %}"></script>-->
    
    <script src="{% static 'bower_components/jquery.formset.js' %}"></script>
    
    <!-- kendo UI -->
    <script src="{% static 'assets/js/kendoui_custom.min.js' %}"></script>

    <!--  kendoui functions -->
    <script src="{% static 'assets/js/pages/kendoui.min.js' %}"></script>
     <!-- ionrangeslider -->
    <script src="{% static 'bower_components/ion.rangeslider/js/ion.rangeSlider.min.js' %}"></script>
    <!--  forms advanced functions -->
    <script src="{% static 'assets/js/pages/forms_advanced.min.js' %}"></script>
    
    <script>
         var is_member = $("#id_is_external").is(':checked');
        console.log("Member Select "+is_member)
        
        if (is_member) {
            $("#member_wrap").hide();
            $("#non_member").show();
            
        }else{
            $("#member_wrap").show();
            $("#non_member").hide();
            
        }
        
    
        $("#id_is_external").on('ifChecked', function(){
             $("#member_wrap").hide();
            $("#non_member").show();
           
        });
            
        $('#id_is_external').on('ifUnchecked', function () {
           $("#member_wrap").show()
            $("#non_member").hide()
           
        })
        UIkit.datepicker("#id_training_start", {maxDate:get_current_date(), format:'YYYY-MM-DD HH:MM:SS' });
        
        $("#id_training_start").attr("autocomplete", "off");
        var total_price = $("#id_training_start")
        var unit_price = $("#id_training_start")
        
        
        UIkit.datepicker("#id_training_end", {maxDate:get_current_date(), format:'YYYY-MM-DD  HH:MM:SS' });
        
        $("#id_training_start").attr("autocomplete", "off");
        var total_price = $("#id_training_end")
        var unit_price = $("#id_training_end")
        
        function get_current_date(){
            var fullDate = new Date()
            console.log(fullDate);
            //Thu May 19 2011 17:25:38 GMT+1000 {}
             
            //convert month to 2 digits
            var twoDigitMonth = ((fullDate.getMonth().length+1) === 1)? (fullDate.getMonth()+1) : '0' + (fullDate.getMonth()+1);
             
            var currentDate = fullDate.getFullYear() + "-" + twoDigitMonth + "-" + (fullDate.getDate()+1);
            console.log(currentDate);
            return currentDate;
         }
        
        $("#selec_adv_1").selectize({plugins:{remove_button:{label:""}},maxItems:null,valueField:"id",labelField:"title",searchField:"title",create:!1,render:{option:function(t,e){return'<div class="option"><span class="title">'+e(t.title)+"</span></div>"},item:function(t,e){return'<div class="item"><a href="'+e(t.url)+'" target="_blank">'+e(t.title)+"</a></div>"}},onDropdownOpen:function(t){t.hide().velocity("slideDown",{begin:function(){t.css({"margin-top":"0"})},duration:200,easing:easing_swiftOut})},onDropdownClose:function(t){t.show().velocity("slideUp",{complete:function(){t.css({"margin-top":""})},duration:200,easing:easing_swiftOut})}});
        
        
       
        
    </script>
{% endblock %}