conf/urls.py
from django.conf.urls import url

from conf.views import *

urlpatterns = [
     url(r'sms/template/$', MessageTemplatesView.as_view(), name='sms_template'),
     url(r'district/list/$', DistrictListView.as_view(), name='district_list'),
     url(r'district/create/$', DistrictCreateView.as_view(), name='district_create'),
     url(r'district/(?P<pk>[\w]+)/$', DistrictUpdateView.as_view(), name='district_edit'),
     url(r'district/delete/(?P<pk>[\w]+)/$', DistrictDeleteView.as_view(), name='district_delete'),
     url(r'county/create/$', CountyCreateView.as_view(), name='county_create'),
     url(r'county/list/$', CountyListView.as_view(), name='county_list'),
     url(r'county/(?P<pk>[\w]+)/$', CountyUpdateView.as_view(), name='county_edit'),

     url(r'sc/create/$', SubCountyCreateView.as_view(), name='subcounty_create'),
     url(r'sc/list/$', SubCountyListView.as_view(), name='subcounty_list'),
     url(r'sc/(?P<pk>[\w]+)/$', SubCountyUpdateView.as_view(), name='subcounty_edit'),
     url(r'village/create/$', VillageCreateView.as_view(), name='village_create'),
     url(r'village/list/$', VillageListView.as_view(), name='village_list'),
     url(r'village/(?P<pk>[\w]+)/$', VillageUpdateView.as_view(), name='village_edit'),
     url(r'payment/create/$', PaymentModeCreateView.as_view(), name='payment_create'),
     url(r'payment/list/$', PaymentModeListView.as_view(), name='payment_list'),
     url(r'payment/(?P<pk>[\w]+)/$', PaymentModeUpdateView.as_view(), name='payment_edit'),
     
     url(r'upload/location/$', LocationUploadView.as_view(), name='location_upload'),
    ]

product/urls.py
from django.conf.urls import url

from product.views import *

urlpatterns = [

      url(r'item/category/edit/(?P<pk>[\w]+)/$', ItemCategoryUpdateView.as_view(), name='item_category_update'),
      url(r'item/category/list/$', ItemCategoryListView.as_view(), name='item_category_list'),
      url(r'item/category/create/$', ItemCategoryCreateView.as_view(), name='item_category_create'),

      url(r'item/price/(?P<pk>[\w]+)/$', get_item_price, name='item_price'),
      url(r'item/edit/(?P<pk>[\w]+)/$', ItemUpdateView.as_view(), name='item_update'),
      url(r'item/list/$', ItemListView.as_view(), name='item_list'),
      url(r'item/create/$', ItemCreateView.as_view(), name='item_create'),

      url(r'supplier/edit/(?P<pk>[\w]+)/$', SupplierUpdateView.as_view(), name='supplier_update'),
      url(r'supplier/list/$', SupplierListView.as_view(), name='supplier_list'),
      url(r'supplier/create/$', SupplierCreateView.as_view(), name='supplier_create'),

      url(r'commission/list/$', SalesCommissionListView.as_view(), name='commission_list'),
      url(r'commission/create/$', SalesCommissionCreateView.as_view(), name='commission_create'),
      url(r'commission/edit/(?P<pk>[\w]+)/$', SalesCommissionUpdateView.as_view(), name='commission_update'),

      url(r'supplier/user/list/(?P<supplier>[\w]+)/$', SupplierUserListView.as_view(), name="supplier_user_list"),
      url(r'supplier/user/create/(?P<supplier>[\w]+)/$', SupplierUserCreateView.as_view(), name="supplier_user_create"),

      url(r'price/log/(?P<pk>[\w]+)/$', ProductVariationPriceLogListView.as_view(), name='price_log_list'),
      url(r'price/request/(?P<pk>[\w]+)/$', get_product_price, name='product_price'),
      url(r'price/list/$', ProductVariationPriceListView.as_view(), name='price_list'),
      url(r'price/create/$', ProductVariationPriceCreateView.as_view(), name='price_create'),
      url(r'price/(?P<pk>[\w]+)/$', ProductVariationPriceUpdateView.as_view(), name='price_edit'),
      url(r'variation/list/$', ProductVariationListView.as_view(), name='variation_list'),
      url(r'variation/create/$', ProductVariationView.as_view(), name='variation_create'),
      url(r'variation/(?P<pk>[\w]+)/$', ProductVariationView.as_view(), name='variation_edit'),
      url(r'unit/list/$', ProductUnitListView.as_view(), name='unit_list'),
      url(r'unit/create/$', ProductUnitCreateView.as_view(), name='unit_create'),
      url(r'unit/(?P<pk>[\w]+)/$', ProductUnitUpdateView.as_view(), name='unit_edit'),


      url(r'compute/final/price/$', compute_item_price, name='compute_price'),
      url(r'token/create/$', compute_famunera_token, name='famunera_token'),
]

umis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from conf import urls as conf_urls
from userprofile import urls as profile_urls
from product import urls as product_urls
from coop import urls as coop_urls 
from partner import urls as partner_urls
from operations import urls as op_urls
from endpoint import urls as ep_urls
from messaging import urls as msg_urls
from activity import urls as act_urls
from payment import urls as pay_urls
from credit import urls as credit_urls
from account import urls as account_urls

from dashboard.views import DashboardView
from userprofile.views.authentication import LoginView, LogoutView
from conf.views import Handle404, Handle403

handler404 = Handle404.as_view()
handler403 = Handle403.as_view()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^conf/', include(conf_urls, namespace='conf')),
    url(r'^profile/', include(profile_urls, namespace='profile')),
    url(r'^product/', include(product_urls, namespace='product')),
    url(r'^payment/', include(pay_urls, namespace='payment')),
    url(r'^coop/', include(coop_urls, namespace='coop')),
    url(r'^op/', include(op_urls, namespace='op')),
    url(r'^partner/', include(partner_urls, namespace='partner')),
    url(r'^endpoint/', include(ep_urls, namespace='endpoint')),
    url(r'^messaging/', include(msg_urls, namespace='messaging')),
    url(r'^activity/', include(act_urls, namespace='activity')),
    url(r'^credit/', include(credit_urls, namespace='credit')),
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

product/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User


class Product(models.Model):
    name = models.CharField(max_length=25, unique=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product'
    
    def product_variation(self):
        return ProductVariation.objects.filter(product=self)

    def __unicode__(self):
        return self.name
    

class ProductUnit(models.Model):
    name = models.CharField(max_length=25, unique=True)
    code = models.CharField(max_length=3, unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product_units'
        verbose_name = 'Product Unit'
        verbose_name_plural = 'Product Units'
        
    
    def __unicode__(self):
        return self.name
    

class ProductVariation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    unit = models.ForeignKey(ProductUnit, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product_variation'
        verbose_name = 'Product'
        verbose_name_plural = 'Product'
        unique_together = ['product', 'name']
           
    def __unicode__(self):
        return self.name
    

class ProductVariationPrice(models.Model):
    product = models.ForeignKey(ProductVariation, related_name='variation_price', on_delete=models.CASCADE)
    unit = models.ForeignKey(ProductUnit, null=True, blank=True, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product_variation_price'
        verbose_name = 'Product Price'
        verbose_name_plural = 'Product Prices'
        unique_together = ['product', 'unit']
        
    def __unicode__(self):
        return "%s" % self.product


class ProductVariationPriceLog(models.Model):
    product = models.ForeignKey(ProductVariation, on_delete=models.CASCADE)
    unit = models.ForeignKey(ProductUnit, null=True, blank=True, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product_variation_price_log'
        verbose_name = 'Product Price'
        verbose_name_plural = 'Product Prices'
        
    def __unicode__(self):
        return "%s" % self.product


class Supplier(models.Model):
    name = models.CharField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=32, null=True, blank=True)
    email = models.CharField(max_length=32, null=True, blank=True)
    contact_person = models.CharField(max_length=32, null=True, blank=True)
    contact_person_phone_number = models.CharField(max_length=32, null=True, blank=True)
    logo = models.ImageField(upload_to='supplier/logo/', null=True, blank=True)
    api_url = models.CharField(max_length=255, blank=True, null=True)
    username = models.CharField(max_length=255, blank=True, null=True)
    password = models.CharField(max_length=255, blank=True, null=True)
    token = models.TextField(blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'supplier'
        
    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


class SupplierAdmin(models.Model):
    user = models.OneToOneField(User,  blank=True, related_name='supplier_admin')
    supplier = models.ForeignKey(Supplier, blank=True, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.user.get_full_name()


class ItemCategory(models.Model):
    parent = models.ForeignKey('self', null=True, blank=True)
    category_name = models.CharField(max_length=255)
    category_code = models.CharField(max_length=120, null=True, blank=True, unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "item_category"

    def __unicode__(self):
        return self.category_name


class Item(models.Model):
    name = models.CharField(max_length=255)
    supplier_item_id = models.CharField(unique=True, max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(ItemCategory, null=True)
    supplier = models.ForeignKey(Supplier, null=True, blank=True, on_delete=models.CASCADE)
    allow_loan_request = models.BooleanField(default=False)
    supplier_price = models.DecimalField(max_digits=20, decimal_places=2)
    price = models.DecimalField(max_digits=20, decimal_places=2, verbose_name=u"Retail Price")
    created_by = models.ForeignKey(User, null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'item'

    def __unicode__(self):
        return self.name


class ItemAdditionalCharges(models.Model):
    name = models.CharField(max_length=160)
    charge_type = models.CharField(max_length=36, choices=(('CHARGE', 'CHARGE'), ('DISCOUNT', 'DISCOUNT')))
    value = models.DecimalField(max_digits=12, decimal_places=2)
    value_type = models.CharField(max_length=36, choices=(('AMOUNT', 'AMOUNT'), ('PERCENTAGE', 'PERCENTAGE')))
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'item_addition_charges'

    def __unicode__(self):
        return "{} {}".format(self.value, self.value_type)

    
# @receiver(post_save, sender=ProductVariationPrice)
# def create_price_log(sender, instance, created, **kwargs):
#     if created:
#         ProductVariationPriceLog.objects.create(variation=instance)


class SalesCommission(models.Model):
    supplier = models.ForeignKey(Supplier, null=True, blank=True, on_delete=models.CASCADE)
    category = models.CharField(max_length=64, choices=(('AGENT', 'AGENT'), ('COOPERATIVE', 'COOPERATIVE')))
    commission_value = models.DecimalField(max_digits=12, decimal_places=2)
    transaction_type = models.CharField(max_length=64, choices=(('PERCENT', 'PERCENT'), ('AMOUNT', 'AMOUNT')))
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'sale_commission'
        unique_together = ['supplier', 'category']

    def __unicode__(self):
        return self.commission_value


@receiver(post_save, sender=ProductVariationPrice)
def save_price_log(sender, instance, **kwargs):
    ProductVariationPriceLog.objects.create(product=instance.product,
                                            price=instance.price,
                                            unit=instance.unit,
                                            created_by=instance.created_by) 

product/forms.py
from django import forms

from conf.utils import bootstrapify
from product.models import *

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name']


class ProductUnitForm(forms.ModelForm):
    class Meta:
        model = ProductUnit
        fields = ['name', 'code']
        
        
class ProductVariationForm(forms.ModelForm):
    class Meta:
        model = ProductVariation
        fields = ['name', 'unit']


class ProductVariationPriceForm(forms.ModelForm):
    class Meta:
        model = ProductVariationPrice
        fields = ['product', 'unit', 'price']
        
class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        exclude = ['create_date', 'update_date']


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        exclude = ['create_date', 'update_date']

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request", None)
        super(ItemForm, self).__init__(*args, **kwargs)
        if hasattr(request.user, 'supplier_admin'):
            self.fields['supplier'].widget = forms.HiddenInput()
            self.fields['supplier'].initial = 1

    def clean(self):
        supplier_price = self.cleaned_data.get('supplier_price')
        price = self.cleaned_data.get('price')
        if supplier_price > price:
            raise forms.ValidationError('Supplier price cannot be higher than the retail price')


class SupplierUserForm(forms.ModelForm):
    confirm_password = forms.CharField(max_length=150, required=True, widget=forms.PasswordInput)
    password = forms.CharField(max_length=150, required=True, widget=forms.PasswordInput)
    msisdn = forms.CharField(max_length=150)

    def __init__(self, *args, **kwargs):
        instance = kwargs.pop("instance", None)
        print(instance)
        super(SupplierUserForm, self).__init__(*args, **kwargs)
        if instance:
            self.fields.pop('password')
            self.fields.pop('confirm_password')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'msisdn', 'is_active', 'username', 'password',
                  'confirm_password']


class SalesCommissionForm(forms.ModelForm):
    class Meta:
        model = SalesCommission
        exclude = ['create_date', 'update_date']


class ItemAdditionChargesForm(forms.ModelForm):
    class Meta:
        model = ItemAdditionalCharges
        exclude = ['create_date', 'update_date']


class ItemCategoryForm(forms.ModelForm):
    class Meta:
        model = ItemCategory
        exclude = ['create_date', 'update_date']

       
bootstrapify(SupplierForm)
bootstrapify(ItemForm)
bootstrapify(ItemCategoryForm)
bootstrapify(ItemAdditionChargesForm)
bootstrapify(ProductForm)
bootstrapify(ProductUnitForm)
bootstrapify(ProductVariationForm)
bootstrapify(ProductVariationPriceForm)
bootstrapify(SupplierUserForm)
bootstrapify(SalesCommissionForm)

product/templates/product/item_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form humanize %}

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Item List</h2>
        </div>
        <div class="uk-width-medium-1-2">

            <a href="{% url 'product:item_create' %}" class="md-btn md-btn-success uk-float-right">Add Item</a>
            <a href="{% url 'product:item_category_list' %}" class="md-btn md-btn-success uk-float-right">Add Category</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Supplier</th>
                        <th>Price</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                <td>{{ item.supplier }}</td>
                                <td>{{ item.price|intcomma }}</td>
                                <td>
                                    <a href="{% url 'product:item_update' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/itemcategory_form.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
<h3 class="heading_b uk-margin-bottom">Item Form</h3>
    <form method="POST" class="new-event-form" role="role">
       <div class="md-card">
            <div class="md-card-content">
                {% csrf_token %}
                {% include "error_template.html" with form=form %}

                 <div class="uk-grid" data-uk-grid-margin>
                    <div class="uk-width-medium-1-2">
                        {% for field in form %}
                            {% include "form/field.html" with field=field input_group_add_on='<i class="uk-input-group-icon uk-icon-key"></i>' %}
                        {% endfor %}
                    </div>
                </div>
        </div>
        <div class="md-card">
            <div class="md-card-content">
                <div class="md-card-body">
                    <div class="uk-grid">
                        <div class="uk-width-1-1">
                            <button type="submit" class="md-btn md-btn-success">Submit</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </form>
{% endblock %}

product/templates/product/itemcategory_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Item List</h2>
        </div>
        <div class="uk-width-medium-1-2">

            <a href="{% url 'product:item_category_create' %}" class="md-btn md-btn-success uk-float-right">Add Category</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Parent</th>
                        <th>Code</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.category_name }}</td>
                                <td>{{ item.parent }}</td>
                                <td>{{ item.category_code }}</td>
                                
                                <td>
                                    <a href="{% url 'product:item_category_update' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/productvariation_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Product List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:variation_create' %}" class="md-btn md-btn-success uk-float-right">Add Product</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Type</th>
                        <th>Product</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                <td>
                                   
                                    {% for variation in item.product_variation %}
                                        <div><strong>- {{ variation }}</strong><div>
                                    {% endfor %}
                                
                                </td>
                                <td>
                                    <!--<a href="#"><i class="md-icon material-icons"></i></a>
                                    <a href="#"><i class="md-icon material-icons">detail</i></a>-->
                                   <a href="{% url 'product:variation_edit' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right"><i class="md-icon material-icons"></i>Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/productvariationprice_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Product Price List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:price_create' %}" class="md-btn md-btn-success uk-float-right">Add Price</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Product</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.product }}</td>
                                <td>
                                  {{ item.price }} per {{ item.unit }}<div>
                                </td>
                                <td>
                                    <!--<a href="#"><i class="md-icon material-icons"></i></a>
                                    <a href="#"><i class="md-icon material-icons">detail</i></a>-->
                                   <a href="{% url 'product:price_edit' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right"><i class="md-icon material-icons"></i>Adjust</a>
                                   <a href="{% url 'product:price_log_list' item.product.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right"><i class="md-icon material-icons"></i>Price Log</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/salescommission_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load material_form %}

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Commission List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:commission_create' %}" class="md-btn md-btn-success uk-float-right">Add Commission</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Supplier</th>
                        <th>Category</th>
                        <th>Commission</th>
                        <th>Transaction Type</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.supplier }}</td>
                                <td>{{ item.category }}</td>
                                <td>{{ item.commission_value|intcomma }}</td>
                                <td>{{ item.transaction_type }}</td>

                                <td>
                                    <a href="{% url 'product:commission_update' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Edit</a>
                              </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/supplier_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Supplier List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:supplier_create' %}" class="md-btn md-btn-success uk-float-right">Add Supplier</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                
                                <td>
                                    <a href="{% url 'product:supplier_update' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Edit</a>
                                    <a href="{% url 'product:supplier_user_list' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Add Users</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/supplieradmin_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Supplier User List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:supplier_user_create' id %}" class="md-btn md-btn-success uk-float-right">Add Supplier User</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item }}</td>
                                <td>
                                    <a href="{% url 'product:supplier_user_create' item.supplier.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}