conf/urls.py
from django.conf.urls import url

from conf.views import *

urlpatterns = [
     url(r'sms/template/$', MessageTemplatesView.as_view(), name='sms_template'),
     url(r'district/list/$', DistrictListView.as_view(), name='district_list'),
     url(r'district/create/$', DistrictCreateView.as_view(), name='district_create'),
     url(r'district/(?P<pk>[\w]+)/$', DistrictUpdateView.as_view(), name='district_edit'),
     url(r'district/delete/(?P<pk>[\w]+)/$', DistrictDeleteView.as_view(), name='district_delete'),
     url(r'county/create/$', CountyCreateView.as_view(), name='county_create'),
     url(r'county/list/$', CountyListView.as_view(), name='county_list'),
     url(r'county/(?P<pk>[\w]+)/$', CountyUpdateView.as_view(), name='county_edit'),

     url(r'sc/create/$', SubCountyCreateView.as_view(), name='subcounty_create'),
     url(r'sc/list/$', SubCountyListView.as_view(), name='subcounty_list'),
     url(r'sc/(?P<pk>[\w]+)/$', SubCountyUpdateView.as_view(), name='subcounty_edit'),
     url(r'village/create/$', VillageCreateView.as_view(), name='village_create'),
     url(r'village/list/$', VillageListView.as_view(), name='village_list'),
     url(r'village/(?P<pk>[\w]+)/$', VillageUpdateView.as_view(), name='village_edit'),
     url(r'payment/create/$', PaymentModeCreateView.as_view(), name='payment_create'),
     url(r'payment/list/$', PaymentModeListView.as_view(), name='payment_list'),
     url(r'payment/(?P<pk>[\w]+)/$', PaymentModeUpdateView.as_view(), name='payment_edit'),
     
     url(r'upload/location/$', LocationUploadView.as_view(), name='location_upload'),
    ]

umis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from conf import urls as conf_urls
from userprofile import urls as profile_urls
from product import urls as product_urls
from coop import urls as coop_urls 
from partner import urls as partner_urls
from operations import urls as op_urls
from endpoint import urls as ep_urls
from messaging import urls as msg_urls
from activity import urls as act_urls
from payment import urls as pay_urls
from credit import urls as credit_urls
from account import urls as account_urls

from dashboard.views import DashboardView
from userprofile.views.authentication import LoginView, LogoutView
from conf.views import Handle404, Handle403

handler404 = Handle404.as_view()
handler403 = Handle403.as_view()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^conf/', include(conf_urls, namespace='conf')),
    url(r'^profile/', include(profile_urls, namespace='profile')),
    url(r'^product/', include(product_urls, namespace='product')),
    url(r'^payment/', include(pay_urls, namespace='payment')),
    url(r'^coop/', include(coop_urls, namespace='coop')),
    url(r'^op/', include(op_urls, namespace='op')),
    url(r'^partner/', include(partner_urls, namespace='partner')),
    url(r'^endpoint/', include(ep_urls, namespace='endpoint')),
    url(r'^messaging/', include(msg_urls, namespace='messaging')),
    url(r'^activity/', include(act_urls, namespace='activity')),
    url(r'^credit/', include(credit_urls, namespace='credit')),
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

conf/forms.py
from django import forms

from conf.models import District, County, SubCounty, Village, Parish, PaymentMethod, MessageTemplates
from conf.utils import bootstrapify

class DistrictForm(forms.ModelForm):
    class Meta:
        model = District
        fields = ['name']


class CountyForm(forms.ModelForm):
    class Meta:
        model = County
        fields = ['district', 'name']


class SubCountyForm(forms.ModelForm):
    class Meta:
        model = SubCounty
        fields = ['county', 'name']
        
class VillageForm(forms.ModelForm):
    class Meta:
        model = Parish
        fields = ['name', 'sub_county']
        
        
class PaymentMethodForm(forms.ModelForm):
    class Meta:
        model = PaymentMethod
        fields = ['method']
        
        
class UploadLocation(forms.Form):
    
    sheetChoice = (
        ('1','sheet1'),
        ('2','sheet2'),
        ('3','sheet3'),
        ('4','sheet4'),
        ('5','sheet5'),
    )
    
    rowchoices = (
        ('1', 'Row 1'),
        ('2', 'Row 2'),
        ('3', 'Row 3'),
        ('4', 'Row 4'),
        ('5', 'Row 5')
        )
    
    choices = list()
    for i in range(65, 91):
        choices.append([i-65, chr(i)])

    
    uploadfile = forms.FileField(label="Excel File", max_length=100)
    sheet = forms.ChoiceField(label="Sheet", choices=sheetChoice, widget=forms.Select(attrs={'class':'form-control'}))
    row = forms.ChoiceField(label="Row", choices=rowchoices, widget=forms.Select(attrs={'class':'form-control'}))
    district_col = forms.ChoiceField(label='District Column', initial=0, choices=choices, widget=forms.Select(attrs={'class':'form-control'}), help_text='The column containing the District')
    county_col = forms.ChoiceField(label='County Column', initial=1, choices=choices, widget=forms.Select(attrs={'class':'form-control'}), help_text='The column containing the County')
    sub_county_col = forms.ChoiceField(label='Sub County Column', initial=2, choices=choices, widget=forms.Select(attrs={'class':'form-control'}), help_text='The column containing the Sub County')
    parish_col = forms.ChoiceField(label='Parish Column', initial=3, choices=choices, widget=forms.Select(attrs={'class':'form-control'}), help_text="The column contains the Parish")
    clear_data = forms.BooleanField(initial=False, required=False, help_text="Select to Clear the Saved Data")


class MessageTemplatesForm(forms.ModelForm):
    class Meta:
        model = MessageTemplates
        exclude = ['create_date', 'update_date']
    
bootstrapify(DistrictForm)
bootstrapify(SubCountyForm)
bootstrapify(VillageForm)
bootstrapify(PaymentMethodForm)
bootstrapify(UploadLocation)
bootstrapify(MessageTemplatesForm)
bootstrapify(CountyForm)

conf/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import re
import xlrd

from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.db import transaction
from django.db.models import Q, Count, Sum
from django.utils.encoding import smart_str
from django.views.generic import ListView, View, TemplateView, DeleteView
from django.views.generic.edit import CreateView, UpdateView

from conf.utils import log_debug, log_error, get_deleted_objects
from conf.models import District, County, SubCounty, Parish, Village, PaymentMethod, MessageTemplates
from conf.forms import DistrictForm, CountyForm, SubCountyForm, VillageForm, PaymentMethodForm, UploadLocation,\
MessageTemplatesForm

class ExtraContext(object):
    extra_context = {}

    def get_context_data(self, **kwargs):
        context = super(ExtraContext, self).get_context_data(**kwargs)
        context['active'] = ['_config']
        context['title'] = 'System Settings'
        context.update(self.extra_context)
        return context


class DistrictListView(ExtraContext, ListView):
    model = District
    extra_context = {'active': ['_config', '__district']}
    

class DistrictCreateView(ExtraContext, CreateView):
    model = District
    form_class = DistrictForm
    extra_context = {'active': ['_config', '__district']}
    success_url = reverse_lazy('conf:district_list')


class DistrictUpdateView(ExtraContext, UpdateView):
    model = District
    form_class = DistrictForm
    extra_context = {'active': ['_config', '__district']}
    success_url = reverse_lazy('conf:district_list')


class DistrictDeleteView(ExtraContext, DeleteView):
    model = District
    success_url = reverse_lazy('conf:district_list')
    template_name='confirm_delete.html'

    def get_context_data(self, **kwargs):
        #
        context = super(DistrictDeleteView, self).get_context_data(**kwargs)
        #

        deletable_objects, model_count, protected = get_deleted_objects([self.object])
        #
        context['deletable_objects'] = deletable_objects
        context['model_count'] = dict(model_count).items()
        context['protected'] = protected
        #
        return context


class CountyListView(ExtraContext, ListView):
    model = County
    extra_context = {'active': ['_config', '__county']}


class CountyCreateView(ExtraContext, CreateView):
    model = County
    form_class = CountyForm
    extra_context = {'active': ['_config', '__county']}
    success_url = reverse_lazy('conf:county_list')


class CountyUpdateView(ExtraContext, UpdateView):
    model = County
    form_class = CountyForm
    extra_context = {'active': ['_config', '__county']}
    success_url = reverse_lazy('conf:county_list')


class SubCountyListView(ExtraContext, ListView):
    model = SubCounty
    extra_context = {'active': ['_config', '__sub_county']}
    
    
class SubCountyCreateView(ExtraContext, CreateView):
    model = SubCounty
    form_class = SubCountyForm
    extra_context = {'active': ['_config', '__sub_county']}
    success_url = reverse_lazy('conf:subcounty_list')


class SubCountyUpdateView(ExtraContext, UpdateView):
    model = SubCounty
    form_class = SubCountyForm
    extra_context = {'active': ['_config', '__sub_county']}
    success_url = reverse_lazy('conf:subcounty_list')
    

class VillageListView(ExtraContext, ListView):
    model = Parish
    template_name = "conf/village_list.html"
    order_by = '-name'
    extra_context = {'active': ['_config', '__village']}
    # paginate_by = 10
        
    def get_queryset(self):
        queryset = None
        village = self.request.GET.get('village')
        subcounty = self.request.GET.get('subcounty')
        county = self.request.GET.get('county')
        district = self.request.GET.get('district')
        queryset = Parish.objects.all()
        if village:
            queryset = queryset.filter(name=query)
        if subcounty:
            queryset = queryset.filter(sub_county__name=subcounty)
        if county:
            queryset = queryset.filter(sub_county__county__name=county)
        if district:
            queryset = queryset.filter(sub_county__county__district__name=district)
            
        return queryset
        
    def get_context_data(self, **kwargs):
        context = super(VillageListView, self).get_context_data(**kwargs)
        return context
    

class VillageCreateView(ExtraContext, CreateView):
    model = Parish
    template_name = "conf/village_form.html"
    form_class = VillageForm
    extra_context = {'active': ['_config', '__village']}
    success_url = reverse_lazy('conf:village_list')

class VillageUpdateView(ExtraContext, UpdateView):
    model = Parish
    template_name = "conf/village_form.html"
    form_class = VillageForm
    extra_context = {'active': ['_config', '__village']}
    success_url = reverse_lazy('conf:village_list')
    

class PaymentModeListView(ExtraContext, ListView):
    model = PaymentMethod
    extra_context = {'active': ['_config', '__sub_county']}
    

class PaymentModeCreateView(ExtraContext, CreateView):
    model = PaymentMethod
    form_class = PaymentMethodForm
    extra_context = {'active': ['_config', '__payment_method']}
    success_url = reverse_lazy('conf:payment_list')

class PaymentModeUpdateView(ExtraContext, UpdateView):
    model = PaymentMethod
    form_class = PaymentMethodForm
    extra_context = {'active': ['_config', '__payment_method']}
    success_url = reverse_lazy('conf:payment_list')


class LocationUploadView(ExtraContext, View):

    # @method_decorator(is_authorized(all=['system.add_location']))
    # def dispatch(self, *args, **kwargs):
    #     return super(LocationUploadView, self).dispatch(*args, **kwargs)

    template_name = 'conf/location_upload.html'
    
    def dispatch(self, request, *args, **kwargs):
        #messages.success(self.request, "Book viewed!")
        extra_context = {'active': ['_config', '__village']}
        return super(LocationUploadView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = UploadLocation
        return render(request, self.template_name, {'active': 'setting', 'form':form})
    
    def post(self, request, *args, **kwargs):
        
        form = UploadLocation(request.POST, request.FILES)
        
        if form.is_valid():
            f = request.FILES['uploadfile']
            
            path = f.temporary_file_path()
            index = int(form.cleaned_data['sheet'])-1
            startrow = int(form.cleaned_data['row'])-1
            district_col = int(form.cleaned_data['district_col'])
            county_col = int(form.cleaned_data['county_col'])
            sub_county_col = int(form.cleaned_data['sub_county_col'])
            parish_col = int(form.cleaned_data['parish_col'])
            clear_data = form.cleaned_data['clear_data']            
    
            book = xlrd.open_workbook(filename=path, logfile='/tmp/xls.log')
            sheet = book.sheet_by_index(index)
            rownum = 0
            data = dict()
            locations = []
            for i in range(startrow, sheet.nrows):
                try:
                    row = sheet.row(i)
                    rownum = i+1
                    district = smart_str(row[district_col].value).strip()
        
                    if not re.search('^[A-Z\s\(\)\-\.]+$', district, re.IGNORECASE):
                        if (i+1) == sheet.nrows: break
                        data['errors'] = '"%s" is not a valid District (row %d)' % \
                        (district, i+1)
                        return render(request, self.template_name, {'active': 'system', 'form':form, 'error': data})
        
                    county = smart_str(row[county_col].value).strip()
        
                    if not re.search('^[A-Z\s\(\)\-\.]+$', county, re.IGNORECASE):
                        data['errors'] = '"%s" is not a valid County (row %d)' % \
                        (county, i+1)
                        return render(request, self.template_name, {'active': 'system', 'form':form, 'error': data})
                    
                    sub_county = smart_str(row[sub_county_col].value).strip()
        
                    if not re.search('^[A-Z\s\(\)\-\.]+$', sub_county, re.IGNORECASE):
                        data['errors'] = '"%s" is not a valid Sub County (row %d)' % \
                        (sub_county, i+1)
                        return render(request, self.template_name, {'active': 'system', 'form':form, 'error': data})
                    
                    parish = smart_str(row[parish_col].value).strip()
        
                    if not re.search('^[A-Z\s\(\)\-\.]+$', parish, re.IGNORECASE):
                        data['errors'] = '"%s" is not a valid Parish (row %d)' % \
                        (parish, i+1)
                        return render(request, self.template_name, {'active': 'system', 'form':form, 'error': data})
                    
                    q = {'district': district, 'county': county,'sub_county':sub_county, 'parish': parish}
                    locations.append(q)
             
                except Exception as err:
                    log_error()
                    return render(request, self.template_name, {'active': 'setting', 'form':form, 'error': err})
            try:
                with transaction.atomic():
                    if clear_data:
                        District.objects.all().delete()
                        County.objects.all().delete()
                        SubCounty.objects.all().delete()
                    dcount = 0
                    ccount = 0
                    sccount = 0
                    pcount = 0
                    for d in locations:
                        district = d['district'].title()
                        county = d['county'].title()
                        sub_county = d['sub_county'].title()

conf/templates/conf/county_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">County List</h4>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'conf:county_create' %}" class="md-btn md-btn-success uk-float-right">Add County</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table  id="dt_tableTools"  class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>District</th>
                       <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                <td>{{ item.district }}</td>
                               
                                <td>
                                     <a href="{% url 'conf:county_edit' item.id %}"  class="uk-float-right"><i class="md-icon material-icons">&#xE254;</i></a>
                                    <!--<a href="#"><i class="md-icon material-icons">&#xE88F;</i></a>-->
                                    
                                </td>
                            </tr>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="md-fab-wrapper md-fab-in-card">
                <a class="md-fab md-fab-wave" href="#"><i class="material-icons">&#xE52E;</i></a>
            </div>
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <!-- datatables -->
    <script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <!-- datatables colVis-->
    <script src="{% static 'bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
<!-- datatables tableTools-->
    <script src="{% static 'bower_components/datatables-tabletools/js/dataTables.tableTools.js' %}"></script>
    <!-- datatables custom integration -->
    <script src="{% static 'assets/js/custom/datatables_uikit.min.js' %}"></script>

    <!--  datatables functions -->
    <script src="{% static 'assets/js/pages/plugins_datatables.min.js' %}"></script>
{% endblock %}

conf/templates/conf/district_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">District</h4>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'conf:district_create' %}" class="md-btn md-btn-success uk-float-right">Add District</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table id="dt_tableTools" class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                       
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                
                                <td>
                                {% if request.user.is_superuser %}<a href="{% url 'conf:district_delete' item.id %}" class="uk-float-right"><i class="md-icon material-icons uk-text-danger">&#xe872;</i></a>{% endif %}
                                    <a href="{% url 'conf:district_edit' item.id %}" class="uk-float-right"><i class="md-icon material-icons ">&#xE254;</i></a>
                                </td>

                            </tr>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
           
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <!-- datatables -->
    <script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <!-- datatables colVis-->
    <script src="{% static 'bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
<!-- datatables tableTools-->
    <script src="{% static 'bower_components/datatables-tabletools/js/dataTables.tableTools.js' %}"></script>
    <!-- datatables custom integration -->
    <script src="{% static 'assets/js/custom/datatables_uikit.min.js' %}"></script>

    <!--  datatables functions -->
    <script src="{% static 'assets/js/pages/plugins_datatables.min.js' %}"></script>
{% endblock %}

conf/templates/conf/http404.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
<h3 class="heading_b uk-margin-bottom">Oops!</h3>
   <div class="md-card">
        <div class="md-card-content">
            Sorry, what you are looking for was not found. Error Code 404. 
        </div>
    </div>
{% endblock %}

conf/templates/conf/paymentmethod_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">Payment Method List</h4>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'conf:payment_create' %}" class="md-btn md-btn-success uk-float-right">Add Payment Method</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Payment Method</th>
                        <th></th>
                       <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.method }}</td>
                                <td></td>
                                <td>
                                     <a href="{% url 'conf:payment_edit' item.id %}"  class="uk-float-right"><i class="md-icon material-icons">&#xE254;</i></a>
                                    <!--<a href="#"><i class="md-icon material-icons">&#xE88F;</i></a>-->
                                </td>
                            </tr>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

conf/templates/conf/subcounty_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">Sub County List</h4>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'conf:subcounty_create' %}" class="md-btn md-btn-success uk-float-right">Add Sub County</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table  id="dt_tableTools"  class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>County</th>
                       <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                <td>{{ item.county }}</td>
                               
                                <td>
                                     <a href="{% url 'conf:subcounty_edit' item.id %}"  class="uk-float-right"><i class="md-icon material-icons">&#xE254;</i></a>
                                    <!--<a href="#"><i class="md-icon material-icons">&#xE88F;</i></a>-->
                                    
                                </td>
                            </tr>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="md-fab-wrapper md-fab-in-card">
                <a class="md-fab md-fab-wave" href="#"><i class="material-icons">&#xE52E;</i></a>
            </div>
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <!-- datatables -->
    <script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <!-- datatables colVis-->
    <script src="{% static 'bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
<!-- datatables tableTools-->
    <script src="{% static 'bower_components/datatables-tabletools/js/dataTables.tableTools.js' %}"></script>
    <!-- datatables custom integration -->
    <script src="{% static 'assets/js/custom/datatables_uikit.min.js' %}"></script>

    <!--  datatables functions -->
    <script src="{% static 'assets/js/pages/plugins_datatables.min.js' %}"></script>
{% endblock %}

conf/templates/conf/village_list.html
{% extends 'base.html' %}
{% load static %}
{% load el_pagination_tags %}
{% block style %}
<style type="text/css">
    .row-pagination{
        margin: 15px;
    }
    .row-pagination a{
        padding: 10px;
        border-radius: 4px;
    }

    .endless_page_current{
        background: #7cb342;
        color: #fff;
        padding: 10px;
        border-radius: 4px;
    }

</style>
{% endblock %}

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">Village List</h4>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'conf:village_create' %}" class="md-btn md-btn-success uk-float-right">Add Village</a>
            <a href="{% url 'conf:location_upload' %}" class="md-btn md-btn-success uk-float-right">Upload File</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="dt-uikit-header">
                <form action="" method="get">
                    <div class="uk-grid">
                        <div class="uk-width-medium-1-1">
                            <div class="uk-input-group">
                                <div class="uk-grid">
                                <div class="uk-width-medium-1-2">
                                    <label>Village:</label>
                                    <input type="text" name="village" class="md-input" />
                                </div>
                                <div class="uk-width-medium-1-2">
                                    <label>Sub Country:</label>
                                    <input type="text" name="subcounty" class="md-input" />
                                </div>
                                <div class="uk-width-medium-1-2">
                                    <label>County:</label>
                                    <input type="text" name="county" class="md-input" />
                                </div>
                                <div class="uk-width-medium-1-2">
                                    <label>District:</label>
                                    <input type="text" name="district" class="md-input" />
                                </div>
                                 </div>
                                <span class="uk-input-group-addon">
                                    <button type="submit" class="md-btn"><i class="material-icons">search</i></button>
                                </span>
                                <span class="uk-input-group-addon">
                                    <a href="." class="md-btn"><i class="material-icons">refresh</i></a>
                                </span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <p></p>
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Sub County</th>
                       <th>County</th>
                       <th>District</th>
                       <th></th>
                    </tr>
                    </thead>
                    <tbody>
                       {% paginate object_list %}{% get_pages %}
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                <td>{{ item.sub_county }}</td>
                                <td>{{ item.sub_county.county }}</td>
                                <td>{{ item.sub_county.county.district }}</td>
                               
                                <td>
                                     <a href="{% url 'conf:subcounty_edit' item.id %}"  class="uk-float-right"><i class="md-icon material-icons">&#xE254;</i></a>
                                    <!--<a href="#"><i class="md-icon material-icons">&#xE88F;</i></a>-->
                                    
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
           <!-- {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
  {% endif %}-->
            <div class="row-pagination">
                Showing entries
                {{ pages.current_start_index }}-{{ pages.current_end_index }} of
                {{ pages.total_count }}.
                {# Just print pages to render the Digg-style pagination. #}
                {% show_pages %}
            </div>
            
        </div>
    </div>
{% endblock %}