conf/urls.py
from django.conf.urls import url

from conf.views import *

urlpatterns = [
     url(r'sms/template/$', MessageTemplatesView.as_view(), name='sms_template'),
     url(r'district/list/$', DistrictListView.as_view(), name='district_list'),
     url(r'district/create/$', DistrictCreateView.as_view(), name='district_create'),
     url(r'district/(?P<pk>[\w]+)/$', DistrictUpdateView.as_view(), name='district_edit'),
     url(r'district/delete/(?P<pk>[\w]+)/$', DistrictDeleteView.as_view(), name='district_delete'),
     url(r'county/create/$', CountyCreateView.as_view(), name='county_create'),
     url(r'county/list/$', CountyListView.as_view(), name='county_list'),
     url(r'county/(?P<pk>[\w]+)/$', CountyUpdateView.as_view(), name='county_edit'),

     url(r'sc/create/$', SubCountyCreateView.as_view(), name='subcounty_create'),
     url(r'sc/list/$', SubCountyListView.as_view(), name='subcounty_list'),
     url(r'sc/(?P<pk>[\w]+)/$', SubCountyUpdateView.as_view(), name='subcounty_edit'),
     url(r'village/create/$', VillageCreateView.as_view(), name='village_create'),
     url(r'village/list/$', VillageListView.as_view(), name='village_list'),
     url(r'village/(?P<pk>[\w]+)/$', VillageUpdateView.as_view(), name='village_edit'),
     url(r'payment/create/$', PaymentModeCreateView.as_view(), name='payment_create'),
     url(r'payment/list/$', PaymentModeListView.as_view(), name='payment_list'),
     url(r'payment/(?P<pk>[\w]+)/$', PaymentModeUpdateView.as_view(), name='payment_edit'),
     
     url(r'upload/location/$', LocationUploadView.as_view(), name='location_upload'),
    ]

payment/urls.py
from django.conf.urls import url

from payment.views import *

urlpatterns = [
    
    url(r'bulk/delete/(?P<pk>[\w]+)/$', BulkPaymentDelete.as_view(), name='bulk_delete'),
    url(r'bulk/confirm/(?P<pk>[\w]+)/$', BulkPaymentConfirm.as_view(), name='bulk_confirm'),
    url(r'bulk/detail/(?P<pk>[\w]+)/$', BulkPaymentDetail.as_view(), name='bulk_detail'),
    url(r'bulk/list/$', BulkPaymentListView.as_view(), name='bulk_list'),
    url(r'bulk/upload/$', BulkPaymentView.as_view(), name='upload'),
    url(r'edit/(?P<pk>[\w]+)/$', PaymentMethodUpateView.as_view(), name='update'),
    url(r'detail/(?P<pk>[\w]+)/$', PaymentTransactionDetail.as_view(), name='detail'),
    url(r'dowload/$', DownloadPaymentExcelView.as_view(), name='download'),
    url(r'list/$', PaymentMethodListView.as_view(), name='list'),
    url(r'create/$', PaymentTransactionCreateView.as_view(), name='create')
]

umis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from conf import urls as conf_urls
from userprofile import urls as profile_urls
from product import urls as product_urls
from coop import urls as coop_urls 
from partner import urls as partner_urls
from operations import urls as op_urls
from endpoint import urls as ep_urls
from messaging import urls as msg_urls
from activity import urls as act_urls
from payment import urls as pay_urls
from credit import urls as credit_urls
from account import urls as account_urls

from dashboard.views import DashboardView
from userprofile.views.authentication import LoginView, LogoutView
from conf.views import Handle404, Handle403

handler404 = Handle404.as_view()
handler403 = Handle403.as_view()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^conf/', include(conf_urls, namespace='conf')),
    url(r'^profile/', include(profile_urls, namespace='profile')),
    url(r'^product/', include(product_urls, namespace='product')),
    url(r'^payment/', include(pay_urls, namespace='payment')),
    url(r'^coop/', include(coop_urls, namespace='coop')),
    url(r'^op/', include(op_urls, namespace='op')),
    url(r'^partner/', include(partner_urls, namespace='partner')),
    url(r'^endpoint/', include(ep_urls, namespace='endpoint')),
    url(r'^messaging/', include(msg_urls, namespace='messaging')),
    url(r'^activity/', include(act_urls, namespace='activity')),
    url(r'^credit/', include(credit_urls, namespace='credit')),
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

payment/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from coop.models import CooperativeMember, Cooperative

class PaymentAPI():
    pass


class BulkPaymentRequest(models.Model):
    file_name = models.CharField(max_length=255)
    cooperative = models.ForeignKey(Cooperative, blank=True, null=True, on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=32, decimal_places=2)
    payment_method = models.CharField(max_length=18)
    status = models.CharField(max_length=10, choices=(('PROCESSING', 'PROCESSING'),
        ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')))
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_Date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "bulk_payment_request"
        
    def __unicode__(self):
        return self.status or u''
    
    def get_log(self):
        return BulkPaymentRequestLog.objects.filter(bulk_payment_request=self)
    
    
class BulkPaymentRequestLog(models.Model):
    bulk_payment_request = models.ForeignKey(BulkPaymentRequest, on_delete=models.CASCADE)
    member = models.ForeignKey(CooperativeMember, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=32, decimal_places=2)
    payment_method = models.CharField(max_length=18)
    transaction_date = models.DateField()
    process_state = models.CharField(max_length=10, choices=(('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'),
        ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')))
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_Date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'bulk_payment_request_log'
        
    def __unicode__(self):
        return u''


class MemberPayment(models.Model):
    transaction_id = models.CharField(max_length=255)
    cooperative = models.ForeignKey(Cooperative, on_delete=models.CASCADE)
    payemnt_reference = models.CharField(max_length=255, blank=True,)
    member = models.ForeignKey(CooperativeMember, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=32, decimal_places=2)
    payment_date = models.DateTimeField()
    payment_method = models.CharField(max_length=10, choices=(('CASH', 'CASH'), ('BANK', 'BANK'), ('MOBILE MONEY', 'MOBILE MONEY')))
    user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    status = models.CharField(max_length=15, choices=(('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')), blank=True)
    request = models.TextField(blank=True)
    response = models.TextField(blank=True)
    response_date = models.DateTimeField(blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "member_payment"
        
    def __unicode__(self):
        return self.payemnt_reference
    

class MobileMoneyRequest(models.Model):
    transaction_reference = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=25)
    member = models.ForeignKey(CooperativeMember, blank=True, null=True, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=32, decimal_places=2)
    status = models.CharField(max_length=15, choices=(('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')), blank=True)
    request = models.TextField(blank=True)
    response = models.TextField(blank=True)
    response_date = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "mobile_money_request"
        
    def __unicode__(self):
        return self.phone_number
    
    
class MemberPaymentTransaction(models.Model):
    cooperative = models.ForeignKey(Cooperative, blank=True, null=True, on_delete=models.CASCADE)
    member = models.ForeignKey(CooperativeMember, blank=True, null=True, on_delete=models.CASCADE)
    payment_date = models.DateTimeField()
    transaction_reference = models.CharField(max_length=255)
    payment_method = models.CharField(max_length=16, choices=(('CASH', 'CASH'), ('BANK', 'BANK'), ('MOBILE MONEY', 'MOBILE MONEY')))
    status = models.CharField(max_length=15, choices=(('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')), blank=True)
    balance_before = models.DecimalField(max_digits=32, decimal_places=2, blank=True, null=True)
    amount = models.DecimalField(max_digits=32, decimal_places=2)
    balance_after = models.DecimalField(max_digits=32, decimal_places=2, blank=True, null=True)
    creator = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    transaction_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "member_payment_transaction"
        
    def __unicode__(self):
        return "%s" % self.transaction_reference
    
    

payment/forms.py
import xlrd
from django import forms
from os.path import splitext
from conf.utils import bootstrapify
from payment.models import MemberPaymentTransaction
from coop.models import CooperativeMember, Cooperative

class MemberPaymentForm(forms.ModelForm):
    class Meta:
        model = MemberPaymentTransaction
        fields = ['cooperative', 'member', 'amount', 'payment_date', 'payment_method']
        
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(MemberPaymentForm, self).__init__(*args, **kwargs)
        
        self.fields['member'].queryset = CooperativeMember.objects.none()
        
        if 'cooperative' in self.data:
            try:
                cooperative_id = int(self.data.get('cooperative'))
                self.fields['member'].queryset = CooperativeMember.objects.filter(cooperative=cooperative_id).order_by('first_name')
            except Exception as e: #(ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            if self.instance.cooperative:
                self.fields['member'].queryset = self.instance.cooperative.member_set.order_by('first_name')
        

class BulkPaymentForm(forms.Form):
    sheetChoice = (
        ('1','sheet1'),
        ('2','sheet2'),
        ('3','sheet3'),
        ('4','sheet4'),
        ('5','sheet5'),
    )
    
    rowchoices = (
        ('1', 'Row 1'),
        ('2', 'Row 2'),
        ('3', 'Row 3'),
        ('4', 'Row 4'),
        ('5', 'Row 5')
        )
    
    choices = list()
    for i in range(65, 91):
        choices.append([i-65, chr(i)])
        
    cooperative = forms.ChoiceField(widget=forms.Select())
    payment_method = forms.ChoiceField(widget=forms.Select(), choices=(('', '------------'), ('CASH', 'CASH'), ('BANK', 'BANK'), ('MOBILE MONEY', 'MOBILE MONEY')))
    excel_file = forms.FileField()
    sheet = forms.ChoiceField(label="Sheet", choices=sheetChoice, widget=forms.Select(attrs={'class':'form-control'}))
    row = forms.ChoiceField(label="Row", choices=rowchoices, widget=forms.Select(attrs={'class':'form-control'}))
    phone_number_col = forms.ChoiceField(label='Phone Number Column', initial=0, choices=choices, widget=forms.Select(attrs={'class':'form-control'}), help_text='The column containing the Members Phone Number')
    amount_col = forms.ChoiceField(label='Amount Column', initial=1, choices=choices, widget=forms.Select(attrs={'class':'form-control'}), help_text='The column containing the Transaction Amount')
    transaction_date_col = forms.ChoiceField(label='Transaction Date Column', initial=2, choices=choices, required=False, widget=forms.Select(attrs={'class':'form-control'}), help_text='The column containing the Transaction Date')
    
    def __init__(self, *args, **kwargs):
        super(BulkPaymentForm, self).__init__(*args, **kwargs)
        choices = [['','------------']]
        choices.extend([[c.id, c.name] for c in Cooperative.objects.all()])
        self.fields['cooperative'].choices = choices
    
    
    def clean(self):
        data = self.cleaned_data
        f = data.get('excel_file', None)
        ext = splitext(f.name)[1][1:].lower()
        if not ext in ["xlsx", "xls"]:
            raise forms.ValidationError(("The File type is not accepted"))
        return data


class PaymentFilterForm(forms.Form):
    search = forms.CharField(max_length=255, required=False)
    start_date = forms.CharField(max_length=160, required=False, widget=forms.TextInput(attrs={"data-uk-datepicker":"{format:'YYYY-MM-DD'}"}))
    end_date = forms.CharField(max_length=160, required=False, widget=forms.TextInput(attrs={"data-uk-datepicker":"{format:'YYYY-MM-DD'}"}))
    
    cooperative = forms.ChoiceField(widget=forms.Select(), required=False)
    payment_method = forms.ChoiceField(widget=forms.Select(), required=False, choices=(('', '------------'), ('CASH', 'CASH'), ('BANK', 'BANK'), ('MOBILE MONEY', 'MOBILE MONEY')))
    status = forms.ChoiceField(widget=forms.Select(), required=False, choices=(('', '------------'), ('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')))
  
    def __init__(self, *args, **kwargs):
        super(PaymentFilterForm, self).__init__(*args, **kwargs)
        choices = [['','------------']]
        choices.extend([[c.id, c.name] for c in Cooperative.objects.all()])
        self.fields['cooperative'].choices = choices

bootstrapify(MemberPaymentForm)
bootstrapify(BulkPaymentForm)
bootstrapify(PaymentFilterForm)
        
    

payment/templates/payment/bulkpaymentrequest_detail.html
{% extends 'base.html' %}
{% load static %}
{% load my_custom_tags %}

{% block page_content %}

        <div class="md-card-content">
<div class="uk-width-large-7-10 uk-row-first">
<div class="md-card md-card-single main-print" id="invoice" style="opacity: 1; transform: scale(1);">
    <div id="invoice_preview">
        <div class="md-card-toolbar">
            <div class="md-card-toolbar-actions hidden-print" style="padding-top: 0px !important;">
                
                <a href="{% url 'payment:bulk_list' %}" class="md-btn md-btn-primary uk-margin-small-top">Back</a>
                {% if object.status != 'COMPLETED'%}
                    <button href="#" id="id_cancel" class="md-btn md-btn-danger uk-margin-small-top" onclick="UIkit.modal.confirm('Are you sure you want to continue with this transaction?', function(){ cancel_confirm(); });">CANCEL</button>
                    <button href="#" id="id_submit" class="md-btn md-btn-success uk-margin-small-top" onclick="UIkit.modal.confirm('Are you sure you want to continue with this transaction?', function(){ confirm(); });">CONFIRM</button>
                {% endif %}
                
            </div>
            <h3 class="md-card-toolbar-heading-text large" id="invoice_name">
                Bulk Payment Request
            </h3>
        </div>
        <div class="md-card-content" style="">
            
            <div class="uk-margin-medium-bottom">
                <span class="uk-text-muted uk-text-small uk-text-italic">Date:</span> {{object.create_Date}}
                <br>
                <!--<span class="uk-text-muted uk-text-small uk-text-italic">Due Date:</span> 02.01.2019-->
            </div>
            <div class="uk-grid" data-uk-grid-margin="">
                <div class="uk-width-small-3-5 uk-row-first">
                    <div class="uk-margin-medium-bottom">
                        <span class="uk-text-muted uk-text-small uk-text-italic">Cooperative</span>
                        <p> <strong>{{ object.cooperative}}</strong></p>
                        <!--<p class="uk-text-small uk-text-muted uk-margin-top-remove">Incl. VAT - $862.85</p>-->
                    </div>
                    <div class="uk-margin-bottom">
                        <span class="uk-text-muted uk-text-small uk-text-italic">Payment Method:</span>
                        <address>
                            <p id="id_payment_method"><strong>{{ object.payment_method }}</strong></p>
                       </address>
                    </div>
                    <div class="uk-margin-medium-bottom">
                        <span class="uk-text-muted uk-text-small uk-text-italic">Status:</span>
                        <address>
                            <p><strong>{{ object.status }} </strong></p>
                            
                        </address>
                    </div>
                    <div class="uk-margin-medium-bottom">
                        <span class="uk-text-muted uk-text-small uk-text-italic">File:</span>
                        <address>
                            <p><strong>{{ object.file_name }} </strong></p>
                            
                        </address>
                    </div>
                </div>
                <div class="uk-width-small-2-5">
                    <div class="uk-margin-medium-bottom">
                        <span class="uk-text-muted uk-text-small uk-text-italic">Total Amount:</span>
                        <p class="heading_b uk-text-success">{{ object.total_amount}}</p>
                        <!--<p class="uk-text-small uk-text-muted uk-margin-top-remove">Incl. VAT - $862.85</p>-->
                    </div>
                    
                </div>
            </div>
            <div class="uk-grid uk-margin-large-bottom">
                <div class="uk-width-1-1">
                    <div class="uk-overflow-container">
                        <table  id="dt_tableTools" class="uk-table uk-table-striped">
                            <thead>
                            <tr class="uk-text-upper">
                                <th>Member</th>
                                <th>Phone Number</th>
                                <th>Amount</th>
                                <th>Status</th>
                                <th>Sent Date</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for item in object.get_log %}
                                    <tr class="uk-table-middle">
                                        <td class="uk-text-center">{{ item.member }}</td>
                                        <td class="uk-text-center">{{ item.member.phone_number }}</td>
                                        <td class="uk-text-center">{{ item.amount }}</td>
                                        <td class="uk-text-center">{{ item.process_state }}</td>
                                        <td class="uk-text-center">{{ item.update_date| date:"d, M Y" }}</td>
                                    </tr>
                                {% endfor %}
                               
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    <div id="invoice_form"></div>
</div>
</div>

</div>

{% endblock %}
{% block page_specific_scripts %}
<script>
    function confirm(){
         var modal = UIkit.modal.blockUI('<div class=\'uk-text-center\'>Please wait...<br/><img class=\'uk-margin-top\' src=\'{% static "assets/img/spinners/spinner.gif" %}\' alt=\'\'>');
         
         $.ajax({                       // initialize an AJAX request
            url: "{% url 'payment:bulk_confirm' object.id %}",
            method: "POST",
            dataType: "json",
            data: {
                'payment_method': "{{ object.payment_method }}" ,
                'csrftoken': getCookie('csrftoken')// add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                console.log(data);        // replace the contents of the city input with the data that came from the server
                //var res = JSON.parse(data);
                modal.hide();
                UIkit.modal.confirm(data.message, function(){ window.location.href = "{% url 'payment:list' %}"; });
            }
        });
    }
    
    function cancel_confirm(){
         var modal = UIkit.modal.blockUI('<div class=\'uk-text-center\'>Please wait...<br/><img class=\'uk-margin-top\' src=\'{% static "assets/img/spinners/spinner.gif" %}\' alt=\'\'>');
         
         $.ajax({                       // initialize an AJAX request
            url: "{% url 'payment:bulk_delete' object.id %}",
            method: "POST",
            dataType: "json",
            data: {
                'csrftoken': getCookie('csrftoken')// add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                console.log(data);        // replace the contents of the city input with the data that came from the server
                //var res = JSON.parse(data);
                modal.hide();
                UIkit.modal.confirm(data.message, function(){ window.location.href = "{% url 'payment:bulk_list' %}"; });
            }
        });
    }
    
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
            }
        }
    });
    </script>
 <!-- datatables -->
    <script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <!-- datatables colVis-->
    <script src="{% static 'bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
    <!-- datatables custom integration -->
    <script src="{% static 'assets/js/custom/datatables_uikit.min.js' %}"></script>

    <!--  datatables functions -->
    <script src="{% static 'assets/js/pages/plugins_datatables.min.js' %}"></script>
    
    
{% endblock %}

payment/templates/payment/memberpaymenttransaction_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %}
{% load el_pagination_tags %}
{% block style %}
<style type="text/css">
    .row-pagination{
        margin: 15px;
    }
    .row-pagination a{
        padding: 10px;
        border-radius: 4px;
    }

    .endless_page_current{
        background: #7cb342;
        color: #fff;
        padding: 10px;
        border-radius: 4px;
    }

</style>
{% endblock %}

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">Payments</h4>
        </div>
        <div class="uk-width-medium-1-2 uk-text-right">
            <a href="#" id="download_excel" class="md-btn md-btn-primary ">Download Excel</a>
            <a href="{% url 'payment:bulk_list' %}" class="md-btn md-btn-success ">Bulk Payment</a>
            {% if request.user.profile.is_union %}
                 <a href="{% url 'payment:create' %}" class="md-btn md-btn-success ">Add Payment</a>
            {% endif %}
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <form class="" method="get">
            <div class="uk-grid" data-uk-grid-margin>
                {% for field in form %}
                    <div class="uk-width-medium-1-5">
                        {% include 'form/field.html' with field=field %}
                    </div>
                {% endfor %}
            </div>
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-5 uk-right">
                </div>
                <div class="uk-width-medium-5 uk-float-right">
                    <button class="md-btn" name="_search" > Search </button>
                    <a href="." class="md-btn md-btn-small md-btn-flat md-btn-flat-primary  uk-margin-small-left"><i class="material-icons md-24 " title="Delete">refresh</i></a>
                    <!--<button class="md-btn md-btn-success uk-float-right" name="_download" value="download"> Export CSV </button>-->
                </div>
             </div>
            </form>
            </div>
        <hr class="uk-grid-divider">
        <div class="md-card-content">
            
            <div class="uk-overflow-container">
                <table id="dt_tableTools" class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Payment Date</th>
                        <th>Coop</th>
                        <th>Member</th>
                        <th>Amount</th>
                        <th>Reference</th>
                        <th>Status</th>
                        <th>Payment Method</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% paginate object_list %}{% get_pages %}
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.payment_date| date:"d, M Y" }}</td>
                               <td>{{ item.cooperative }}</td>
                                <td>{{ item.member }}</td>
                                <td>{{ item.amount }}</td>
                                <td>{{ item.transaction_reference }}</td>
                                <td>{% include 'status_text.html' with field=item.status %}</td>
                                <td>{{ item.payment_method }}</td>
                                <td><a href="{% url 'payment:detail' item.id %}" class="md-btn md-btn-success uk-margin-small-top uk-float-right" >Detail</a></td>
                            </tr>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="row-pagination">
                Showing entries
                {{ pages.current_start_index }}-{{ pages.current_end_index }} of
                {{ pages.total_count }}.
                {# Just print pages to render the Digg-style pagination. #}
                {% show_pages %}
            </div>
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
<script>
    $("#download_excel").on('click', function(e){
            var qstring = window.location.search.replace("?", "");
            var url = "{% url 'payment:download' %}"+"?download=csv&";
            //var urlParams = new URLSearchParams(window.location.search);
            var furl = url+qstring;
           
            window.location = furl
            //$.get(furl, function(data, status){
            //    alert("Data: " + data + "\nStatus: " + status);
            //});
            
        });
    $("#id_start_date").attr("autocomplete", "off");
    $("#id_end_date").attr("autocomplete", "off");
</script>
 <!-- datatables -->
    <script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <!-- datatables colVis-->
    <script src="{% static 'bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
<!-- datatables tableTools-->
    <script src="{% static 'bower_components/datatables-tabletools/js/dataTables.tableTools.js' %}"></script>
    <!-- datatables custom integration -->
    <script src="{% static 'assets/js/custom/datatables_uikit.min.js' %}"></script>

    <!--  datatables functions -->
    <script src="{% static 'assets/js/pages/plugins_datatables.min.js' %}"></script>
{% endblock %}